transaction_graph:
  target: "{{ env_var('PROFILE_TARGET') }}"
  outputs:
    prod:
      type: postgres
      threads: 1
      host: "{{ env_var('POSTGRES_HOST') }}"
      port: "{{ env_var('POSTGRES_PORT') | as_number }}"
      user: "{{ env_var('POSTGRES_USER') }}"
      pass: "{{ env_var('POSTGRES_PASSWORD') }}"
      dbname: "{{ env_var('POSTGRES_DBNAME') }}"
      schema: "{{ env_var('POSTGRES_SCHEMA') }}"